edition = "2021"

max_width = 100
tab_spaces = 4
hard_tabs = false

newline_style = "Unix"
use_small_heuristics = "Max"

use_field_init_shorthand = true

reorder_imports = true
reorder_modules = true

match_block_trailing_comma = true
