[build.env]
passthrough = ["RUSTFLAGS", "RUST_BACKTRACE"]

[target.x86_64-unknown-linux-musl]
# image = "ghcr.io/you/veeox-cross:musl"

[target.aarch64-unknown-linux-gnu]
# image = "ghcr.io/you/veeox-cross:aarch64"
