[package]
name = "fuzz"
edition = "2021"
publish = false

[workspace]
members = ["."]

[package.metadata]
cargo-fuzz = true

[dependencies]
demo = { path = "../crates/demo" }
libfuzzer-sys = "0.4.10"

[[bin]]
name = "demo"
path = "fuzz_targets/demo.rs"
bench = false
test = false
doc = false
