
# cargo-vet config file

[cargo-vet]
version = "0.10"

[[exemptions.aho-corasick]]
version = "1.1.4"
criteria = "safe-to-run"

[[exemptions.alloca]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.anes]]
version = "0.1.6"
criteria = "safe-to-run"

[[exemptions.anstyle]]
version = "1.0.13"
criteria = "safe-to-run"

[[exemptions.arbitrary]]
version = "1.4.2"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.5.0"
criteria = "safe-to-run"

[[exemptions.bumpalo]]
version = "3.19.1"
criteria = "safe-to-run"

[[exemptions.cast]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.cc]]
version = "1.2.52"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.ciborium]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.ciborium-io]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.ciborium-ll]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.clap]]
version = "4.5.54"
criteria = "safe-to-run"

[[exemptions.clap_builder]]
version = "4.5.54"
criteria = "safe-to-run"

[[exemptions.clap_lex]]
version = "0.7.6"
criteria = "safe-to-run"

[[exemptions.criterion]]
version = "0.8.1"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.8.1"
criteria = "safe-to-run"

[[exemptions.crossbeam-deque]]
version = "0.8.6"
criteria = "safe-to-run"

[[exemptions.crossbeam-epoch]]
version = "0.9.18"
criteria = "safe-to-run"

[[exemptions.crossbeam-utils]]
version = "0.8.21"
criteria = "safe-to-run"

[[exemptions.crunchy]]
version = "0.2.4"
criteria = "safe-to-run"

[[exemptions.either]]
version = "1.15.0"
criteria = "safe-to-run"

[[exemptions.find-msvc-tools]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.half]]
version = "2.7.1"
criteria = "safe-to-run"

[[exemptions.itertools]]
version = "0.13.0"
criteria = "safe-to-run"

[[exemptions.itoa]]
version = "1.0.17"
criteria = "safe-to-run"

[[exemptions.jobserver]]
version = "0.1.34"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.83"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.180"
criteria = "safe-to-deploy"

[[exemptions.libfuzzer-sys]]
version = "0.4.10"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.6"
criteria = "safe-to-run"

[[exemptions.num-traits]]
version = "0.2.19"
criteria = "safe-to-run"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-run"

[[exemptions.oorandom]]
version = "11.1.5"
criteria = "safe-to-run"

[[exemptions.page_size]]
version = "0.6.0"
criteria = "safe-to-run"

[[exemptions.plotters]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.proc-macro2]]
version = "1.0.105"
criteria = "safe-to-run"

[[exemptions.quote]]
version = "1.0.43"
criteria = "safe-to-run"

[[exemptions.r-efi]]
version = "5.3.0"
criteria = "safe-to-deploy"

[[exemptions.rayon]]
version = "1.11.0"
criteria = "safe-to-run"

[[exemptions.rayon-core]]
version = "1.13.0"
criteria = "safe-to-run"

[[exemptions.regex]]
version = "1.12.2"
criteria = "safe-to-run"

[[exemptions.regex-automata]]
version = "0.4.13"
criteria = "safe-to-run"

[[exemptions.regex-syntax]]
version = "0.8.8"
criteria = "safe-to-run"

[[exemptions.rustversion]]
version = "1.0.22"
criteria = "safe-to-run"

[[exemptions.same-file]]
version = "1.0.6"
criteria = "safe-to-run"

[[exemptions.serde]]
version = "1.0.228"
criteria = "safe-to-run"

[[exemptions.serde_core]]
version = "1.0.228"
criteria = "safe-to-run"

[[exemptions.serde_derive]]
version = "1.0.228"
criteria = "safe-to-run"

[[exemptions.serde_json]]
version = "1.0.149"
criteria = "safe-to-run"

[[exemptions.shlex]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.114"
criteria = "safe-to-run"

[[exemptions.tinytemplate]]
version = "1.2.1"
criteria = "safe-to-run"

[[exemptions.unicode-ident]]
version = "1.0.22"
criteria = "safe-to-run"

[[exemptions.walkdir]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.wasip2]]
version = "1.0.1+wasi-0.2.4"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.106"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.106"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.106"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.106"
criteria = "safe-to-run"

[[exemptions.web-sys]]
version = "0.3.83"
criteria = "safe-to-run"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-run"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.winapi-util]]
version = "0.1.11"
criteria = "safe-to-run"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.windows-link]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.61.2"
criteria = "safe-to-run"

[[exemptions.wit-bindgen]]
version = "0.46.0"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.33"
criteria = "safe-to-run"

[[exemptions.zerocopy-derive]]
version = "0.8.33"
criteria = "safe-to-run"

[[exemptions.zmij]]
version = "1.0.12"
criteria = "safe-to-run"
