name: Sanitizer

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

concurrency:
  group: sanitizer-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sanitizer:
    uses: ./.github/workflows/_base.yml
    with: { profile: nightly, command: ci-sanitizer }
